[package]
name = "afo-hid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1"

usbd-hid = "0.5.2"
usbd-hid-macros = "0.5.2"   

serde = { version = "1", default-features = false }

