[package]
name = "afo-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = { version = "0.3.0", optional = true }
serde = { version = "1.0.*", default-features = false, features = ["derive"] }

[dev-dependencies]
postcard = "0.7.2"

